// Categories actions types
export const CATEGORIES_ACTION_TYPES = {
  FETCH_CATEGORIES_START: "categpry/FETCH_CATEGORIES_START",
  FETCH_CATEGORIES_SUCCESS: "categpry/FETCH_CATEGORIES_SUCCESS",
  FETCH_CATEGORIES_FAILED: "categpry/FETCH_CATEGORIES_FAILED",
};
